

## RAG-Based Nutritional Chat-Bot

A nutritional chatbot based on retrieval augmented pipeline.

In [4]:
import os

if "COLAB_GPU" in os.environ:
  print("[INFO] Running google Colab, installing requirements")
  !pip install PyMuPDF #for reading PDFS
  !pip install tqdm  #for progress bars
  !pip install accelerate
  !pip install bitsandbytes
  !pip install flash-attn --no-build-isolation

[INFO] Running google Colab, installing requirements
Collecting PyMuPDF
  Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 104.9 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.26.6
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.5.1+cu121)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2025.10.5)
Collecting bitsandbytes
  Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.5.1+cu121)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl (59.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 15.1 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.48.2
Collecting flash-attn
  Downloading flash_attn-2.8.3.tar.gz (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 40.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from flash-attn) (2.5.1+cu121)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from flash-attn) (0.8.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->flash-attn) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch->flash-attn) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->flash-attn) (3.0.3)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... done
  Created wheel for flash-attn: filename=flash_attn-2.8.3-cp312-cp312-linux_x86_64.whl size=255984554 sha256=51f6422861ed951b968428adc9fa7406027f73f2145be5e163810df6f459abea
  Stored in directory: /root/.cache/pip/wheels/3d/59/46/f282c12c73dd4bb3c2e3fe199f1a0d0f8cec06df0cccfeee27
Successfully built flash-attn
Installing collected packages: flash-attn
Successfully installed flash-attn-2.8.3

In [1]:
!pip uninstall -y torch torchvision torchaudio transformers sentence-transformers
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -U transformers sentence-transformers

Found existing installation: torch 2.8.0+cu126
Uninstalling torch-2.8.0+cu126:
  Successfully uninstalled torch-2.8.0+cu126
Found existing installation: torchvision 0.23.0+cu126
Uninstalling torchvision-0.23.0+cu126:
  Successfully uninstalled torchvision-0.23.0+cu126
Found existing installation: torchaudio 2.8.0+cu126
Uninstalling torchaudio-2.8.0+cu126:
  Successfully uninstalled torchaudio-2.8.0+cu126
Found existing installation: transformers 4.57.1
Uninstalling transformers-4.57.1:
  Successfully uninstalled transformers-4.57.1
Found existing installation: sentence-transformers 5.1.2
Uninstalling sentence-transformers-5.1.2:
  Successfully uninstalled sentence-transformers-5.1.2
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (780.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 1.2 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.20.1%2Bcu121-cp312-cp312-linux_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 106.9 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu121/torchaudio-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 106.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 105.5 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 53.0 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 97.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 1.4 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.7 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 13.0 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.6 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.7 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.4 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 9.3 MB/s eta 0:00:00
Collecting triton==3.1.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Collecting sympy==1.13.1 (from torch)
  Downloading https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 56.2 MB/s eta 0:00:00
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Installing collected packages: triton, sympy, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, nvidia-cudnn-cu12, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 3.4.0
    Uninstalling triton-3.4.0:
      Successfully uninstalled triton-3.4.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.3
    Uninstalling sympy-1.13.3:
      Successfully uninstalled sympy-1.13.3
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.6.77
    Uninstalling nvidia-nvtx-cu12-12.6.77:
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.3
    Uninstalling nvidia-nccl-cu12-2.27.3:
      Successfully uninstalled nvidia-nccl-cu12-2.27.3
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4
    Uninstalling nvidia-cufft-cu12-11.3.0.4:
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.77
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.4.1
    Uninstalling nvidia-cublas-cu12-12.6.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.17.1 requires transformers, which is not installed.
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.21.5 nvidia-nvtx-cu12-12.1.105 sympy-1.13.1 torch-2.5.1+cu121 torchaudio-2.5.1+cu121 torchvision-0.20.1+cu121 triton-3.1.0
Collecting transformers
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.2 MB/s eta 0:00:00
Collecting sentence-transformers
  Downloading sentence_transformers-5.1.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.5.1+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Downloading transformers-4.57.1-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 135.2 MB/s eta 0:00:00
Downloading sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.0/488.0 kB 35.1 MB/s eta 0:00:00
Installing collected packages: transformers, sentence-transformers
Successfully installed sentence-transformers-5.1.2 transformers-4.57.1

## Document Processing/ Text Processing and Embedding Creation

In [2]:
import os
import requests

pdf_path = "/content/Human-Nutrition.pdf"

if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")
  url= "https://pressbooks.oer.hawaii.edu/humannutrition2/"
  filename=pdf_path
  response = requests.get(url)

  if response.status_code == 200:
    with open(filename, "wb") as file:
      file.write(response.content)
    print(f"The file has been downloaded and saved as {filename}")
  else:
    print(f"Failed to download: {response.statu_code}")
else:
  print(f"File {pdf_path} exists")

File doesn't exist, downloading...
The file has been downloaded and saved as /content/Human-Nutrition.pdf

In [5]:
import fitz #
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
  """ Perform minor formatting on text"""
  cleaned_text = text.replace("\n", " ").strip()
  return cleaned_text


def open_read_pdf( pdf_path: str) -> list[dict]:
  """ Opens PDF file read its conents
      Parameters: pdf_path(str):
      Returns: list[dict] a list of dictionaries each containing page number
  """
  doc = fitz.open(pdf_path) #open a document
  pages_and_texts = []
  for page_number, page in tqdm(enumerate(doc)):
    text= page.get_text()
    text= text_formatter(text) #remove empty spaces
    pages_and_texts.append({"page_number": page_number -41,
                            "page_char_count": len(text),
                            "page_word_count": len(text.split(" ")),
                            "page_sentence_count_raw": len(text.split(". ")),
                            "page_token_count": len(text) / 4,
                            "text": text})
  return pages_and_texts
pages_and_texts = open_read_pdf(pdf_path= pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 93,
  'page_word_count': 22,
  'page_sentence_count_raw': 1,
  'page_token_count': 23.25,
  'text': 'Skip to content [image] Menu Primary Navigation •  Home •  Read •  Sign in •  Search in book:'},
 {'page_number': -40,
  'page_char_count': 145,
  'page_word_count': 23,
  'page_sentence_count_raw': 2,
  'page_token_count': 36.25,
  'text': 'Search Want to create or adapt books like this? Learn more about how Pressbooks supports open publishing practices.  Book Title: Human Nutrition:'}]

In [6]:
import random
random.sample(pages_and_texts, k=3)

[{'page_number': -10,
  'page_char_count': 22,
  'page_word_count': 3,
  'page_sentence_count_raw': 1,
  'page_token_count': 5.5,
  'text': 'Pressbooks on LinkedIn'},
 {'page_number': -15,
  'page_char_count': 106,
  'page_word_count': 16,
  'page_sentence_count_raw': 1,
  'page_token_count': 26.5,
  'text': 'Metadata Title Human Nutrition: 2020 Edition Authors University of Hawai‘i at Mānoa Food Science and Human'},
 {'page_number': -21,
  'page_char_count': 856,
  'page_word_count': 129,
  'page_sentence_count_raw': 11,
  'page_token_count': 214.0,
  'text': '1. Introduction University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 2. Childhood University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 3. Adolescence University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 4. Late Adolescence University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 18. XV. Chapter 15. Lifespan Nutrition in Adulthood 1. Introduction University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 2. Young Adulthood University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 3. Middle Age University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition'}]

In [7]:
import pandas as pd

df= pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,93,22,1,23.25,Skip to content [image] Menu Primary Navigatio...
1,-40,145,23,2,36.25,Search Want to create or adapt books like this...
2,-39,552,90,3,138.00,2020 Edition by University of Hawai‘i at Mānoa...
3,-38,0,1,1,0.00,
4,-37,83,12,1,20.75,Creative Commons Attribution Read Book Content...

In [8]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,32.00,32.00,32.00,32.00,32.00
mean,-25.50,616.06,93.53,7.09,154.02
std,9.38,370.73,55.86,4.63,92.68
min,-41.00,0.00,1.00,1.00,0.00
25%,-33.25,135.25,22.75,1.75,33.81
50%,-25.50,854.50,128.50,10.00,213.62
75%,-17.75,906.25,135.50,11.00,226.56
max,-10.00,954.00,149.00,14.00,238.50

Chunking -  

5 types of chunking
1. Fixedsize chunking
2. Sematic chunking
3. Recursive chunking
4. Structural chunking
5. LLM chunking

Further text processing (splitting pages into sentences)- Fixed size chunking

In [9]:
from spacy.lang.en import English
nlp= English()

nlp.add_pipe("sentencizer")
doc= nlp("This is a sentence. This is another sentence.")
assert len(list(doc.sents))== 2

list(doc.sents)

[This is a sentence., This is another sentence.]

In [10]:
for item in tqdm(pages_and_texts):
  item["sentences"] = list(nlp(item["text"]).sents)
  #all sentences are string
  item["sentences"] = [str(sentence) for sentence in item["sentences"]]
  # count the sentences
  item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/32 [00:00<?, ?it/s]

In [11]:
random.sample(pages_and_texts, k=1)

[{'page_number': -28,
  'page_char_count': 861,
  'page_word_count': 131,
  'page_sentence_count_raw': 14,
  'page_token_count': 215.25,
  'text': '7. Proteins in a Nutshell University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 8. Proteins, Diet, and Personal Choices University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 10. VII. Chapter 7. Alcohol 1. Introduction University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 2. Alcohol Metabolism University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 3. Health Consequences of Alcohol Abuse University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 4. Health Benefits of Moderate Alcohol Intake University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 11. VIII. Chapter 8. Energy 1. Introduction',
  'sentences': ['7.',
   'Proteins in a Nutshell University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 8.',
   'Proteins, Diet, and Personal Choices University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 10.',
   'VII.',
   'Chapter 7.',
   'Alcohol 1.',
   'Introduction University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 2.',
   'Alcohol Metabolism University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 3.',
   'Health Consequences of Alcohol Abuse University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 4.',
   'Health Benefits of Moderate Alcohol Intake University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 11.',
   'VIII.',
   'Chapter 8.',
   'Energy 1.',
   'Introduction'],
  'page_sentence_count_spacy': 14}]

Chunking our sentences together

In [12]:
num_sentence_chunk_size = 10

def split_list(input_list, slice_size: int) -> list[list[str]]:
  """
  splits the input_list into sublists of size slice_size

  """
  return[input_list[i:i+ slice_size] for i in range(0, len(input_list), slice_size)]

#loop through pages and texts

for item in tqdm(pages_and_texts):
  item["sentences_chunks"] = split_list(input_list= item["sentences"], slice_size= num_sentence_chunk_size)

  item["num_chunks"] = len(item["sentences_chunks"])

  0%|          | 0/32 [00:00<?, ?it/s]

In [15]:
df_chunks = pd.DataFrame(pages_and_chunks)
df_chunks.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count
0,-41,Skip to content [image] Menu Primary Navigatio...,93,22,23.25
1,-40,Search Want to create or adapt books like this?,47,9,11.75
2,-40,Learn more about how Pressbooks supports open ...,67,9,16.75
3,-40,Book Title: Human Nutrition:,28,4,7.00
4,-39,2020 Edition by University of Hawai‘i at Mānoa...,384,68,96.00

Splitting each chunk into its own item

In [14]:
import re
pages_and_chunks=[]
for item in tqdm(pages_and_texts):
  for sentence_chunk in item["sentences"]:
    chunk_dict = {}
    chunk_dict["page_number"] = item["page_number"]


    join_sentence_chunk= "".join(sentence_chunk).replace(" ", " ").strip()
    join_sentence_chunk= re.sub(r'\.([A-Z])', r'. \1', join_sentence_chunk)
    chunk_dict["sentence_chunk"] = join_sentence_chunk

    #get stats about chunk
    chunk_dict["chunk_char_count"] = len(join_sentence_chunk)
    chunk_dict["chunk_word_count"] = len(join_sentence_chunk.split(" ")) # Corrected this line
    chunk_dict["chunk_token_count"] = len(join_sentence_chunk) / 4

    pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

  0%|          | 0/32 [00:00<?, ?it/s]

224

In [16]:
random.sample(pages_and_texts, k=1)

[{'page_number': -37,
  'page_char_count': 83,
  'page_word_count': 12,
  'page_sentence_count_raw': 1,
  'page_token_count': 20.75,
  'text': 'Creative Commons Attribution Read Book Contents Show All Contents Hide All Contents',
  'sentences': ['Creative Commons Attribution Read Book Contents Show All Contents Hide All Contents'],
  'page_sentence_count_spacy': 1,
  'sentences_chunks': [['Creative Commons Attribution Read Book Contents Show All Contents Hide All Contents']],
  'num_chunks': 1}]

In [17]:
df= pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count       224.00            224.00            224.00             224.00
mean        -26.32             87.14             13.35              21.78
std           6.57             68.16             10.16              17.04
min         -41.00              2.00              1.00               0.50
25%         -32.00             13.00              2.00               3.25
50%         -26.00            112.00             17.00              28.00
75%         -21.00            124.25             19.00              31.06
max         -10.00            482.00             68.00             120.50

In [18]:
#show random chunk with under 30 tokens
min_token_length= 30
for row in df[df['chunk_token_count'] <= min_token_length].sample(5).iterrows():
  print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

Chunk token count: 2.0 | Text: License:
Chunk token count: 29.5 | Text: Young Adulthood University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 3.
Chunk token count: 25.75 | Text: University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 11.
Chunk token count: 29.75 | Text: Sports Nutrition University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 6.
Chunk token count: 30.0 | Text: Weight Management University of Hawai‘i at Mānoa Food Science and Human Nutrition Program and Human Nutrition Program 4.

In [19]:
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -39,
  'sentence_chunk': "2020 Edition by University of Hawai‘i at Mānoa Food Science and Human Nutrition Program [image] Download this book •  EPUB •  Digital PDF •  Print PDF •  Pressbooks XML Book Description: This textbook serves as an introduction to nutrition for undergraduate students and is the OER textbook for the FSHN 185 The Science of Human Nutrition course at the University of Hawai'i at Mānoa.",
  'chunk_char_count': 384,
  'chunk_word_count': 68,
  'chunk_token_count': 96.0},
 {'page_number': -39,
  'sentence_chunk': 'The book covers basic concepts in human nutrition, key information about essential nutrients, basic nutritional assessment, and nutrition across the lifespan.',
  'chunk_char_count': 158,
  'chunk_word_count': 21,
  'chunk_token_count': 39.5}]

## Embedding Model - mpnet-base-v2

In [20]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-mpnet-base-v2", device="cpu")
sentences = [
    "The Sentence Tranform Library provides an easy and open-source way to create embeddings.",
    "Sentences can be embedded one by one or as alist of strings"
]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [21]:
embeddings= embedding_model.encode(sentences)
embeddings_dict= dict(zip(sentences, embeddings))

for sentence, embedding in embeddings_dict.items():
  print(f"Sentence: {sentence}")
  print(f"Embedding: {embedding}")
  print("")

Sentence: The Sentence Tranform Library provides an easy and open-source way to create embeddings.
Embedding: [-3.33107635e-02  4.89020795e-02 -2.16649193e-02  4.65952009e-02
 -3.72122750e-02 -1.99266169e-02  1.00682490e-02 -6.64003268e-02
 -2.82911886e-03 -9.20438487e-03  3.15448791e-02  3.42672281e-02
 -3.02754920e-02  2.91308817e-02  4.13112305e-02 -6.44592196e-02
  5.46959005e-02  5.94419613e-03 -1.63708441e-02  1.43992975e-02
  4.85667884e-02  4.46756296e-02  3.45884473e-03  4.01629023e-02
 -3.49699636e-03 -4.97740842e-02 -2.05847877e-03 -1.86864287e-02
  5.75393885e-02 -2.26149568e-03 -2.61267275e-02  3.40121775e-03
  4.28933837e-02  5.47245052e-03  9.28902011e-07 -4.64756042e-03
 -3.10724601e-02 -6.86854450e-03  5.59972273e-03  1.56452935e-02
  5.06103821e-02 -6.43509999e-02  4.42699762e-03  4.33632992e-02
 -3.12533416e-02 -9.91237257e-03  4.14486229e-02  1.24321701e-02
  9.18519050e-02  6.56128451e-02 -1.87841877e-02 -1.55328913e-02
 -2.53281835e-03 -1.84446052e-02 -1.93161629e-02  2.07961649e-02
 -4.18732949e-02 -1.00017618e-03 -4.20079147e-03  2.82180160e-02
 -1.02038821e-02  4.76282351e-02 -5.27643738e-03 -4.86277491e-02
  7.15988353e-02 -2.83213928e-02 -6.74922839e-02  1.71888582e-02
  1.36868367e-02  7.79096782e-02  2.13653669e-02 -5.97517285e-03
 -2.77537368e-02  3.39030963e-03  3.13105918e-02  4.05430736e-04
 -5.18584512e-02  1.40669744e-03  7.30088800e-02  2.49536969e-02
 -5.77685097e-03  2.91719474e-02  2.20334493e-02 -3.97996046e-02
 -2.52795708e-03 -3.76245342e-02  4.64338548e-02 -4.63513955e-02
 -1.74851995e-02 -1.52787548e-02 -2.47639641e-02 -1.15057034e-03
  6.23705313e-02 -3.58001292e-02  5.43530192e-03  1.70594901e-02
 -8.33214447e-02 -4.01288867e-02 -1.25968913e-02 -2.87874769e-02
  6.99240789e-02  1.37204984e-02 -1.07407728e-02  3.66495992e-03
 -6.19687848e-02  3.75256240e-02  1.23362103e-02  4.45662811e-03
 -2.61377096e-02 -1.33998599e-02 -4.43590991e-02 -4.17637825e-03
 -5.90980202e-02  3.95268276e-02 -1.05278045e-02 -5.86731285e-02
 -4.88920882e-02  4.63369973e-02 -3.59787829e-02  5.64849284e-03
  2.99724638e-02 -9.82620404e-04  1.72148794e-02  1.85534898e-02
 -1.59917530e-02  2.11047456e-02 -3.19370665e-02 -2.58692424e-03
 -9.70312022e-03  1.91192771e-03 -2.36690082e-02  2.70080250e-02
  5.27257733e-02 -1.33797126e-02 -4.54141274e-02 -1.78009772e-03
  2.33844016e-02 -2.72976831e-02  1.72993373e-02  1.15851862e-02
 -1.54713104e-02  1.46879070e-02 -6.56709867e-03 -6.59748539e-02
  5.56466915e-02 -1.33694364e-02  1.45141771e-02 -5.10440692e-02
  1.68120954e-02  4.06741649e-02 -3.38809825e-02  1.05672814e-01
  9.95343644e-03 -3.45487036e-02 -7.73044005e-02 -3.39488909e-02
  8.97143260e-02  4.83847633e-02  6.68460876e-02  4.40296205e-03
  4.85648438e-02 -1.59724746e-02 -1.67730842e-02  1.92087069e-02
 -1.45761082e-02 -1.10617941e-02 -2.29591802e-02  2.78621446e-03
  1.18851615e-02  8.99767950e-02  5.89222228e-03  7.75290355e-02
  6.93691662e-03  3.30499187e-02  3.27928364e-02  4.35738526e-02
  6.27191886e-02 -2.40368918e-02  7.33522400e-02  2.09012404e-02
 -3.75191942e-02 -5.75786177e-03 -2.94119585e-02  4.34213169e-02
  9.86214262e-03  3.32528464e-02 -3.29996087e-02  7.85579085e-02
  1.53200403e-02  1.90864392e-02 -2.23518033e-02 -3.27956527e-02
 -6.48694159e-03 -3.81762944e-02 -1.32489298e-02  5.41932471e-02
 -3.29643004e-02  5.41632622e-02 -1.01791918e-02 -6.06804416e-02
 -3.79313831e-04  3.68803330e-02 -2.15379591e-03  7.28189573e-02
  5.24493009e-02  1.89375728e-02  2.41469108e-02 -4.48046140e-02
 -1.79832801e-02  5.90531789e-02  3.76759171e-02 -2.06943247e-02
 -1.79336555e-02 -5.42492829e-02  4.85842228e-02  7.94311333e-03
  1.58951245e-02 -1.84870437e-02 -8.41439608e-03  4.06740867e-02
  4.92335819e-02 -4.08904813e-02  1.89563856e-02  3.91771793e-02
  2.04144511e-02 -2.82023642e-02  7.96417147e-03  2.52478402e-02
  1.17099164e-02  4.24854495e-02 -8.82248953e-03  6.44403100e-02
  3.72367837e-02 -3.87939252e-02 -3.48847397e-02  6.06865510e-02
 -2.62212697e-02 -8.23553726e-02  1.50604453e-02 -8.46478194e-02
  7.54253147e-03  1.80892218e-02 -2.53203698e-02 -1.63698141e-02
  1.09236762e-02 -2.76007578e-02  5.63271046e-02 -4.82653528e-02
 -1.06363595e-02  3.82308252e-02  4.90456559e-02 -8.29586573e-03
  5.82164247e-03  5.05154468e-02 -5.43212611e-03 -1.73025019e-02
 -5.20358719e-02  7.60017894e-03  2.40631923e-02 -6.31647464e-03
 -2.77450532e-02 -6.43170299e-03 -9.28527676e-03 -2.84916554e-02
  2.43227533e-03  9.86365485e-04 -1.58062566e-03 -4.23695222e-02
  1.45270023e-02  1.79692414e-02  1.20013431e-02  9.24991909e-03
  2.82101519e-02  8.13608151e-03  2.17958912e-02 -3.27223912e-02
  9.25451424e-03  3.15273809e-03  1.82427932e-02  5.74519522e-02
 -5.23960255e-02 -2.40449645e-02 -5.00512347e-02  2.37650983e-02
 -2.86918133e-02  4.76055406e-02 -6.93428665e-02 -3.18463258e-02
 -3.29756327e-02  1.28450273e-02  6.01226604e-03  1.77887343e-02
  4.90866378e-02 -4.30881158e-02 -5.72563102e-03  9.57348663e-03
  6.94162622e-02  6.15271181e-02 -3.66921537e-03  5.99050112e-02
  5.38402423e-02 -1.03814749e-03 -1.95453558e-02  9.41675995e-03
  2.71589682e-03  5.15724868e-02 -1.56207485e-02 -2.50743479e-02
  5.13151800e-03  1.16665531e-02  2.73080375e-02 -1.16994418e-02
 -4.44115289e-02  1.44568598e-02 -1.72535665e-02 -1.18216062e-02
 -2.42480468e-02  1.79159753e-02 -3.65480781e-02 -1.38596501e-02
  3.73274237e-02  1.17254397e-02  3.65768224e-02 -2.62331478e-02
 -3.13287154e-02 -2.97594313e-02 -4.16134894e-02 -3.46890427e-02
  7.83948228e-02 -1.92846209e-02 -4.79099399e-04  1.17674433e-02
 -1.57187674e-02 -3.81127335e-02  1.93812530e-02  4.97691259e-02
  2.11994983e-02  4.66928957e-03 -2.47681439e-02 -2.69139856e-02
 -1.54570658e-02 -3.60558443e-02 -7.56108854e-03 -5.91243245e-02
 -1.04337186e-02  1.60787422e-02  1.29178353e-02 -9.31285135e-03
 -3.24261524e-02  9.33388155e-03 -1.19520957e-02 -1.76575258e-02
 -9.36500262e-03  5.61903743e-03 -4.36295457e-02  7.17477575e-02
  5.99769577e-02 -4.36037593e-03 -1.90511066e-02  5.12113702e-03
  4.55740206e-02  6.44330122e-03 -3.98681127e-02  1.96089949e-02
 -4.18040976e-02 -2.66649481e-02  1.60885602e-02 -5.47076724e-02
  1.89636312e-02 -8.63505775e-05  2.48229634e-02  9.33545176e-03
 -2.25152653e-02  9.84035507e-02  4.02973182e-02 -1.19184200e-02
  2.48039886e-02 -4.24322635e-02  5.43518476e-02  1.98957929e-03
  4.05127183e-02 -1.31845683e-01 -3.76817100e-02  7.58005353e-03
 -1.77580398e-02  2.14499384e-02  2.83961976e-03 -9.00509022e-03
 -1.05767809e-01  2.49426216e-02  2.18236409e-02  1.68058984e-02
 -4.74595614e-02 -9.48478654e-03 -4.70832437e-02  2.09892145e-03
 -2.53879689e-02 -3.26819457e-02 -4.07921225e-02  3.19405049e-02
 -4.40264754e-02 -7.31440261e-02 -2.68917624e-03  3.59111140e-03
 -5.09149358e-02  4.18130644e-02  2.27606483e-02  4.95282002e-02
  2.50101113e-03 -3.16870883e-02 -4.48354818e-02 -1.42215425e-02
 -7.00972974e-02  4.34403345e-02  4.76331748e-02 -2.58305613e-02
 -3.27705778e-02 -2.59064473e-02  4.16295566e-02 -4.03090790e-02
 -3.10049839e-02  4.31364886e-02  9.11742225e-02  7.10613932e-03
 -2.20838515e-03 -4.51016799e-02  1.81809887e-02  2.02907249e-02
  6.28330410e-02  2.21045557e-02 -1.91474538e-02 -1.34106353e-02
 -9.45623219e-03  3.22013278e-03 -6.29773438e-02 -3.98268476e-02
  2.90225223e-02 -3.30474526e-02  2.90670283e-02 -9.25476775e-02
 -4.64296192e-02  6.38219714e-02  4.27381471e-02  2.80678999e-02
 -6.39245845e-03 -4.54017567e-03  1.13579510e-02 -4.31123413e-02
  1.11149030e-03 -2.03743787e-03  3.51793319e-02  6.35844143e-03
 -1.29972994e-02  3.71178687e-02  4.13746051e-02  5.13235014e-03
 -3.59946676e-02 -5.46135418e-02 -3.60624865e-02  1.30486796e-02
  2.75826063e-02  1.29172802e-02  7.62227783e-03 -2.47393046e-02
  2.67063584e-02  6.64742105e-03  4.16542850e-02 -6.18838631e-02
 -1.11680515e-02  3.14940475e-02 -1.43864760e-02  2.03063563e-02
  4.54748981e-02 -9.03199986e-03 -1.37884577e-03 -6.21927753e-02
  4.94879670e-02  2.43821908e-02 -4.88122962e-02  1.55064305e-02
 -1.39419297e-02 -2.68106954e-03 -1.42745180e-02 -2.49916199e-03
 -2.17893552e-02  1.21613229e-02 -1.01253726e-01 -2.59063523e-02
 -6.77932799e-02  1.77086312e-02  6.82383776e-02  2.45529748e-02
  3.76026845e-03 -1.32848844e-02 -2.57494319e-02  4.37450781e-03
  9.99918766e-03  4.30015363e-02  6.01811297e-02  1.37083442e-03
 -4.84319450e-03  2.23856345e-02 -3.22544388e-02 -1.08748972e-02
 -6.27520233e-02  3.79965035e-03 -3.69047970e-02 -2.57155225e-02
 -2.43717898e-02 -1.64845698e-02 -2.99303811e-02  3.68408933e-02
 -2.37326343e-02  3.46287973e-02 -2.28505973e-02 -1.15214533e-03
  6.44671172e-02 -4.53582639e-03  6.08280562e-02 -1.93415005e-02
 -1.91963129e-02  4.07475196e-02  6.20074309e-02 -4.57296409e-02
 -5.06423414e-03  6.72020297e-03 -3.53543716e-03 -4.01467085e-02
 -5.29937372e-02  5.31723276e-02 -3.42424959e-02  2.42140498e-02
  1.24312546e-02  1.30542144e-02 -5.04420251e-02 -1.61859617e-02
  7.89808016e-03  3.65254581e-02 -2.10357402e-02 -3.56436335e-02
 -3.34930234e-02 -6.91771954e-02 -1.85224470e-02  3.15183848e-02
 -9.00499430e-03  2.17657834e-02  2.81338347e-03  1.17170550e-02
  2.51293313e-02 -3.58162932e-02 -2.37969551e-02  3.49411704e-02
 -1.89954806e-02 -7.72618726e-02 -3.35872062e-02 -4.51171519e-33
 -5.01102507e-02  2.46761814e-02 -4.36799489e-02 -3.93562689e-02
 -1.45798633e-02 -1.46931978e-02  1.30493585e-02  1.29620954e-02
  1.14813410e-02  3.84211391e-02  9.39996168e-03 -1.04199154e-02
  2.81977449e-02  1.54358465e-02  1.99219100e-02  3.48369442e-02
  2.15156991e-02 -4.28076880e-03  1.11712376e-02 -1.44019388e-02
  1.50947571e-02  4.84458320e-02  6.87508434e-02 -3.98450866e-02
 -4.58453875e-03  1.45428367e-02 -2.95650046e-02  1.42861260e-02
  3.18897441e-02  3.77419926e-02 -2.26242971e-02  2.08100788e-02
 -1.67227779e-02  3.12512703e-02 -1.61665399e-02  6.52953163e-02
 -6.27806783e-02 -2.16108616e-02  6.87765032e-02 -2.22058687e-02
 -3.64357643e-02 -6.02035522e-02 -5.39111160e-02 -5.30235432e-02
  2.68171653e-02  9.86845233e-03  3.47498320e-02 -9.32125933e-03
  1.45311537e-03  5.23333298e-03 -8.58650282e-02 -3.87496222e-03
 -1.57222021e-02  2.80150175e-02  1.63594820e-02  2.78779604e-02
  8.59054737e-04 -6.91432878e-03  6.70672534e-03  2.05075718e-03
 -4.86778617e-02  3.28310765e-02  2.74863392e-02 -5.06806001e-02
 -4.62655500e-02  5.98551407e-02 -1.40648773e-02 -3.70030664e-02
 -1.16899544e-02  4.58492562e-02  1.07379369e-02  5.30732758e-02
  5.02260700e-02  7.82778636e-02 -7.44245993e-03  1.46935452e-02
 -2.45009027e-02 -1.61724817e-02  2.53161918e-02  8.35927017e-03
  1.35195190e-02  2.00830065e-02  1.49450237e-02 -6.77536428e-03
 -8.07759259e-03 -9.20081977e-03 -7.22085824e-04 -5.37939183e-02
  4.46329564e-02 -1.79057494e-02 -8.14699940e-03 -4.76189656e-03
  7.75409024e-03 -2.15350725e-02 -2.17936765e-02 -1.11644408e-02
 -1.84222199e-02  2.27555260e-02 -1.37297362e-02  3.50916944e-02
 -9.02044307e-03 -2.66366564e-02 -5.75789297e-03  2.64254213e-05
  2.64510084e-02  1.23179043e-02  4.89233583e-02 -3.50626744e-03
 -7.34038427e-02 -4.71720559e-04 -4.46362561e-03 -3.63793261e-02
 -5.51645905e-02  8.13358091e-03 -1.15352655e-02  2.66544763e-02
 -9.36380588e-03 -1.64552208e-03  3.93887646e-02 -7.96697941e-03
 -3.76824141e-02 -2.30613053e-02  3.48809212e-02  3.38935778e-02
 -1.00567816e-02 -3.03849503e-02 -4.08595651e-02  5.47683723e-02
  4.15924937e-02 -5.06576300e-02  1.35102319e-02 -3.93057329e-04
  1.76904919e-07  5.05832061e-02  5.35187870e-02  4.38524224e-02
  1.58581454e-02 -1.44063532e-02 -2.60508470e-02  8.76841368e-04
  8.55565891e-02 -7.61794718e-03  4.19670902e-02  1.25748664e-02
 -2.58298088e-02  2.73816194e-02  1.55179081e-02 -1.25005886e-01
  1.45787513e-03 -3.72553095e-02 -3.29445526e-02 -7.00991899e-02
  4.07757750e-03  1.26790002e-01  8.40420872e-02  5.27176149e-02
  4.78753746e-02 -1.83457565e-02 -2.33180150e-02  4.06817906e-02
 -1.82012189e-02 -2.22520269e-02 -1.26759512e-02 -2.10868418e-02
 -3.00113335e-02 -3.18197086e-02 -3.56558412e-02 -2.48855017e-02
 -9.33503546e-03  2.16776039e-02  2.28015110e-02  9.53720603e-03
 -7.19997333e-03 -5.93046211e-02 -2.71871481e-02 -1.47945415e-02
 -2.90593188e-02  5.73746599e-02 -5.06897345e-02 -2.45257840e-02
 -4.94744480e-02 -2.45117750e-02  2.77371332e-02  1.64875351e-02
 -1.34089477e-02 -3.14254649e-02  1.66705821e-03  4.69541103e-02
  1.66324489e-02 -4.60785776e-02 -8.84520113e-02 -5.08998446e-02
  1.26579041e-02 -5.77879837e-03 -2.57035401e-02 -2.03726608e-02
 -5.45460312e-03  4.91330065e-02 -1.18767871e-02  3.67869157e-03
  1.76849945e-34  4.33501415e-02  4.49246168e-02  5.64264283e-02
  4.70958725e-02  5.16887642e-02 -4.99579199e-02  1.17611103e-02
  1.69789325e-03  9.80702322e-03 -7.88692832e-02 -3.17759290e-02]

Sentence: Sentences can be embedded one by one or as alist of strings
Embedding: [ 5.38269691e-02 -2.59866547e-02 -3.24637443e-02  5.52872270e-02
 -2.34391615e-02  1.93825439e-02  1.46790817e-02  1.89507008e-02
  5.86560322e-03 -3.52213755e-02  6.45206571e-02  1.25631308e-02
  4.75897081e-02  6.25172723e-03  2.24422999e-02 -8.03091303e-02
  2.72067115e-02 -6.95572747e-03  1.41680473e-02  1.69963110e-02
  2.70644091e-02  8.46783165e-03  1.83512326e-02  1.21608013e-02
 -4.59739240e-03 -7.61112664e-03 -3.94447856e-02 -1.73338037e-02
 -1.92487656e-04 -3.01571433e-02 -3.19445729e-02 -2.01554075e-02
  1.01812426e-02 -6.18466213e-02  1.62752303e-06  1.15548875e-02
 -4.13075276e-02 -2.45722011e-02 -4.29688655e-02  2.73190495e-02
 -2.46717129e-02  1.54584050e-02  3.18683647e-02  1.93448439e-02
 -2.03450322e-02  5.15551940e-02  5.52704632e-02  2.85892244e-02
  5.61854132e-02  6.79179579e-02 -2.31400467e-02 -2.64395848e-02
 -2.91202217e-02 -1.25384694e-02  3.12503725e-02  1.07624484e-02
  2.04770546e-02 -3.48203145e-02 -7.88917067e-04  7.62312561e-02
  2.84288148e-03  4.16671857e-02  1.07073439e-02 -3.04543059e-02
  8.93971696e-03  3.51528847e-03 -5.05404919e-02 -4.72852178e-02
 -2.23342627e-02  9.40821506e-03  4.84114103e-02  6.42385613e-03
  1.20226946e-02  1.43023282e-02  3.61330397e-02 -2.49300376e-02
 -4.49581295e-02  5.41417450e-02  3.93727934e-03  1.11526428e-02
 -4.67144791e-03  2.89108176e-02 -9.64866392e-03 -1.80037897e-02
 -3.14058736e-02 -5.37463501e-02  1.98019985e-02 -4.62061986e-02
 -3.31652947e-02 -2.47423779e-02 -3.96727733e-02 -4.02332060e-02
 -8.91022792e-04 -2.62390170e-02  1.02465143e-02  2.03211978e-02
 -6.31210655e-02 -5.16284928e-02  1.68961082e-02 -5.79927675e-02
  2.80832462e-02  1.29825175e-02 -6.30876468e-03  6.07429119e-03
 -2.41205133e-02  1.45622669e-02 -1.46014756e-03 -3.43862623e-02
 -6.53407946e-02  3.73306312e-02 -4.56913635e-02 -7.16779530e-02
 -7.13676959e-02  1.01943240e-01 -3.81830409e-02 -4.05840166e-02
 -5.38639165e-02  5.10698184e-02  3.86602506e-02  2.94233840e-02
 -9.96632501e-02  5.07099461e-03 -6.44090911e-03  5.92103675e-02
  8.45410023e-03 -2.68509760e-02 -1.07722320e-02  2.38273665e-02
  4.30200063e-02 -7.45938299e-03 -6.32532081e-03  6.09025806e-02
  5.79884276e-02  9.17903893e-03 -2.90570706e-02 -5.63083857e-04
  2.68069897e-02 -1.27945561e-03  1.78249441e-02 -4.61829752e-02
 -5.62541075e-02 -1.79787576e-02 -2.26592943e-02 -1.70953274e-02
  1.45418420e-02  7.43294461e-03 -7.82180578e-03 -4.00169641e-02
  4.21934016e-02  4.30574603e-02 -6.52896836e-02  5.59475534e-02
  1.74725428e-02 -3.65932919e-02 -4.41424958e-02 -4.31842543e-03
  1.24251552e-01  1.63665731e-02  2.45210454e-02  5.90467565e-02
  1.32739414e-02  3.88562377e-03 -1.87247328e-03 -1.89162418e-02
 -2.00909451e-02 -1.14268074e-02  1.23258424e-03  1.29096722e-02
  2.49020848e-02  4.49476875e-02 -4.66491058e-02  7.96644464e-02
  8.66366783e-04  7.75621161e-02  8.32683127e-03  6.56389818e-02
 -1.08633586e-03 -2.30651908e-02  5.06058373e-02  4.97431085e-02
  5.09373546e-02  6.43160865e-02 -1.02008395e-02 -3.68144475e-02
  1.83235947e-02  4.51897085e-02  6.52999505e-02  7.95748830e-03
  1.62157286e-02 -7.38410950e-02 -6.18611462e-02  1.87385995e-02
 -3.89752880e-04 -3.38937081e-02 -2.64610313e-02  4.89986083e-03
 -5.81188463e-02  2.63762027e-02 -2.24376749e-03 -4.72763591e-02
  1.25508662e-03  2.84121335e-02  7.57019175e-03  2.78589223e-02
 -3.63925397e-02  1.25892330e-02  2.54552104e-02 -4.45545986e-02
  9.48031899e-03  4.79902364e-02 -1.54704144e-02  4.49284129e-02
  1.31107448e-02  2.90519278e-03  1.82335656e-02  4.36919247e-04
  1.39787728e-02  2.11683400e-02 -7.59966522e-02  1.71356071e-02
  1.04838926e-02  3.67242731e-02  1.39478659e-02  2.49914378e-02
  4.13536094e-02 -4.86934260e-02 -3.43220904e-02  3.15935053e-02
  3.14518586e-02  1.06363483e-02 -1.76818427e-02  3.53981107e-02
  4.27230336e-02 -7.40248477e-03 -8.83843079e-02  2.31445432e-02
 -6.21312112e-02 -8.77085850e-02 -6.90112915e-03 -7.90787712e-02
  6.32356619e-03 -3.37496363e-02  1.33505967e-02 -1.30067840e-02
 -1.24445977e-02 -5.61332852e-02  4.81755286e-02  1.81857683e-02
 -1.49245849e-02  1.17741562e-02  2.22783373e-03 -1.10938046e-02
 -7.86105078e-03 -1.45393179e-03  5.25584444e-02 -1.72683094e-02
 -3.29610556e-02  5.42547964e-02 -2.39855107e-02  5.53928269e-03
 -1.97175285e-03 -2.87442300e-02 -2.06220616e-02  1.67414658e-02
  1.60104614e-02  5.93207777e-04 -4.37430628e-02 -6.01403937e-02
 -3.84492464e-02  1.80605873e-02 -3.67182051e-03 -1.08772963e-02
  1.63942035e-02  1.20046875e-02  2.85180733e-02 -5.93843684e-03
 -7.94471148e-03  1.68699175e-02  3.30379866e-02  6.28151968e-02
  3.74017879e-02 -6.51776269e-02 -4.16413806e-02  9.07011621e-04
 -4.45624031e-02  5.01960926e-02 -3.62357059e-05 -6.39408603e-02
 -3.89989652e-02  3.43506411e-03  1.50385220e-02 -3.60596995e-03
  2.79264227e-02 -1.06906056e-01  1.57995652e-02 -1.04021961e-02
  8.69491473e-02  8.50658491e-02 -1.99031923e-03  9.71317515e-02
  6.18762523e-03  4.29773098e-03  1.76863670e-02 -1.73514225e-02
  2.19588969e-02  5.18303029e-02 -2.78225541e-02 -5.29562603e-05
  2.67456044e-02  6.75672889e-02  7.99698755e-02  1.72472689e-02
 -2.35967617e-02  4.81675081e-02 -1.23529350e-02  1.27268760e-02
 -5.15075997e-02 -8.71752724e-02 -2.55154446e-02  1.03909010e-02
  2.89724469e-02 -5.68129413e-04  4.91159223e-02 -4.28777412e-02
 -1.00390615e-04 -2.93003637e-02 -5.57425469e-02 -2.71290686e-04
  4.86495234e-02  9.34348907e-03  3.43947932e-02  5.54889888e-02
 -1.92981455e-02 -1.37310755e-02 -2.68638805e-02  2.51256153e-02
  2.69996785e-02 -1.29793324e-02  1.80681478e-02 -1.23370821e-02
 -1.69997141e-02 -4.52518016e-02 -1.41210551e-03 -8.87511075e-02
 -6.61026407e-03 -3.34547600e-04  3.22551802e-02  1.19036492e-02
 -6.41619563e-02 -1.30089959e-02  2.40539219e-02 -4.23347168e-02
 -3.37499715e-02 -1.16122775e-02 -7.50033408e-02  4.84273173e-02
  2.61173397e-02 -5.08793518e-02 -3.41157764e-02 -2.50835214e-02
  7.62544796e-02  1.64703839e-02 -7.86505416e-02  8.35541859e-02
  1.06413197e-02  9.42960940e-03 -1.26857646e-02 -2.35028621e-02
 -5.42140976e-02  2.44660042e-02 -1.56511068e-02 -2.78931484e-02
 -3.10544809e-03  4.92582172e-02  9.64729581e-03  2.44025495e-02
  3.22945714e-02 -1.23524228e-02  1.58564784e-02  1.48559697e-02
  3.86781245e-02 -1.17438987e-01  1.59804542e-02 -1.07273646e-03
 -5.79231530e-02  1.27479164e-02  4.47670966e-02 -5.23349456e-02
 -5.38819470e-02  3.45503017e-02  1.82067100e-02  2.75944788e-02
 -4.92655449e-02 -1.08249858e-02 -5.35853282e-02  6.81496412e-02
 -1.07764509e-02  2.00531743e-02 -5.97876683e-03  9.74873360e-03
  3.26533578e-02 -2.73751747e-02  6.71205577e-03 -5.22618331e-02
  1.67906303e-02 -7.97158387e-03  4.87423688e-03  3.58180888e-02
 -5.35440966e-02 -1.49666639e-02 -1.48391416e-02 -2.21638512e-02
 -3.14710638e-03  2.53686793e-02  2.31109560e-02  4.27673105e-03
 -2.98354891e-03  1.10704219e-02  1.94115117e-02 -2.86210086e-02
 -4.50638495e-03  6.20751418e-02  6.26359582e-02 -1.74156507e-03
 -3.42303468e-03 -4.74986583e-02  8.98950826e-03 -2.65302346e-03
  1.46247456e-02  1.57766659e-02  3.12775723e-03 -1.09159555e-02
 -3.82746905e-02 -2.29785033e-02 -4.26055677e-02 -2.15078536e-02
 -7.56473746e-03 -3.12981680e-02  4.40400764e-02 -7.88706020e-02
 -2.58735754e-02  2.07159948e-02  7.99743757e-02  2.43577641e-02
  1.67034864e-02 -6.56151539e-03 -5.82745112e-03 -3.56604951e-03

In [22]:
from tqdm.auto import tqdm
embedding_model.to("cpu")

## Embed each chunk one by one
for item in tqdm(pages_and_chunks_over_min_token_len):
  item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/68 [00:00<?, ?it/s]

In [24]:
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

In [25]:
text_chunk_embeddings= embedding_model.encode(text_chunks,
                                              batch_size=32,
                                              convert_to_tensor=True)
text_chunk_embeddings

tensor([[ 0.0356,  0.0114, -0.0086,  ..., -0.0059, -0.0095,  0.0303],
        [ 0.0153,  0.0223,  0.0013,  ..., -0.0032, -0.0061, -0.0181],
        [ 0.0371,  0.0343, -0.0160,  ..., -0.0008,  0.0013,  0.0198],
        ...,
        [ 0.0283,  0.0685, -0.0083,  ..., -0.0157,  0.0207, -0.0172],
        [ 0.0435,  0.0134, -0.0119,  ..., -0.0252,  0.0286,  0.0077],
        [ 0.0472,  0.0474,  0.0010,  ..., -0.0244, -0.0135,  0.0012]])

In [27]:
from sentence_transformers import util, SentenceTransformer

embedding_model = SentenceTransformer("all-mpnet-base-v2", device="cpu")

## Retrieval

In [31]:
import torch
query= "micronutrients functions"
print(f"Query: {query}")

query_embedding = embedding_model.encode(query, convert_to_tensor=True)
from time  import perf_counter as timer

start_timer= timer()
dot_scores= util.dot_score(a= query_embedding,b= text_chunk_embeddings)[0]
end_timer= timer()

print(f" Time taken to get scores on {len(text_chunk_embeddings)} embeddings: {end_timer - start_timer: .5f} seconds.")

top_results_dot_product= torch.topk(dot_scores, k=5)
top_results_dot_product

Query: micronutrients functions
 Time taken to get scores on 68 embeddings:  0.00020 seconds.

torch.return_types.topk(
values=tensor([0.5302, 0.5217, 0.4850, 0.4811, 0.4644]),
indices=tensor([ 1, 23, 26, 64, 20]))